services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiBase\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  Maispace\MaiBase\EventListener\SmokeTestContentFilterListener:
    tags:
      - name: event.listener
        identifier: 'mai-base/smoke-test-filter'
        event: TYPO3\CMS\Frontend\Event\AfterContentHasBeenFetchedEvent

  Maispace\MaiBase\EventListener\SmokeTestResolveContentAreasListener:
    tags:
      - name: event.listener
        identifier: 'mai-base/smoke-test-content-areas'
        event: TYPO3\CMS\Core\Page\ResolveContentAreasEvent
        priority: -100
